[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description="flask template"
[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.2.4"
flask = "^1.1.2"
replit = "^3.0.0"
sqlalchemy = "^1.4.15"
